homeassistant:
  name: Home
  latitude:  39.473055912019305
  longitude: -74.50922252018545
  elevation: 15
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  packages: !include_dir_named packages

frontend:
 themes: !include_dir_merge_named themes

config:

recorder:
  db_url: !secret db_url
  purge_keep_days: 90
  exclude:
    domains:
      - weather
      - camera
      - sun
      - automation

conversation:
history:
logbook:
ffmpeg:
map:
sun:
ios:
influxdb:
  host: 192.168.86.105

http:
  api_password:    !secret http_password
  #  ssl_certificate: /ssl/fullchain.pem
  # ssl_key:         /ssl/privkey.pem
  base_url:        https://home.thegrebs.com:443

mqtt:
  broker: core-mosquitto
  username: mqtt
  password: !secret mqtt_pass

updater:
  include_used_components: true

discovery:
  ignore:
    - sabnzbd

hue:
  bridges:
    - host: 192.168.86.201

wink:

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret z_wave_net_key

panel_iframe:
  energy:
    title: Energy
    url: https://solar.thegrebs.com/
    icon: mdi:power-plug
  grafana:
    title: Grafana
    url: https://home.thegrebs.com/grafana/dashboard/db/main
    icon: mdi:speedometer
  z_wave_graph:
    title: 'Z-Wave Graph'
    icon: mdi:vector-square
    url: https://home.thegrebs.com/local/z-wave-graph.html
panel_custom:
  - name: zwavegraph2
    sidebar_title: ZWave Graph2
    sidebar_icon: mdi:access-point-network
    url_path: zwave

shell_command:
  z_wave_graph: /usr/local/bin/python3 /config/bin/z-wave-graph.py

nest:
  client_id:     !secret nest_client_id
  client_secret: !secret nest_client_secret

climate:
  - platform: nest
    username: michael@thegrebs.com
    password: !secret nest_password

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    name: Galloway
  - platform: yweather
    name: Later

sensor:
  - platform: ted5000
    name: main
    host: 192.168.86.50
    port: 80
  - platform: bitcoin
    display_options:
      - exchangerate
  - platform: template
    sensors:
      counter_lights_on:
        unit_of_measurement: 'Lights'
        friendly_name: 'Lights on'
        entity_id:
          - switch.on_air
          - light.kitchen
          - light.kitchen_table
          - light.kitchen_accent
          - light.den
          - fan.den_fan
          - light.front_room
          - light.office
          - light.master_bedroom
          - light.downstairs_hall
          - light.upstairs_hall
        value_template: >
          {% if states('group.all_inside') == 'on' %}
          {% for e in states.group.all_inside.attributes.entity_id if states(e) == 'on'  %}
          {% if loop.last %}
          {{ loop.index }}
          {% endif %}
          {%- endfor -%}
          {% else %}
          0
          {% endif %}
      front_door_status:
        friendly_name: Front Door Status
        entity_id: lock.front_door_lock
        value_template: >-
          {% set lock_status = states.lock.front_door_lock.attributes.lock_status %}
          {% set lock_status = lock_status|replace('user 0', 'Master') %}
          {% set lock_status = lock_status|replace('user 1', 'Kids') %}
          {{ lock_status }}
      electric_usage:
        friendly_name: Electricity Usage
        entity_id: sensor.solar_generation
        unit_of_measurement: kWh
        value_template: '{{ states.sensor.solar_generation.attributes["tot_used"] }}'
      electric_net:
        friendly_name: Net Electricity
        entity_id: sensor.solar_generation
        unit_of_measurement: kWh
        value_template: '{{ ( states.sensor.solar_generation.attributes["tot_used"] -  float(states.sensor.solar_generation.state) ) | round(3) }}'
      living_room_media:
        friendly_name: Living Room Media
        entity_id: remote.living_room
        value_template: '{{ states.remote.living_room.attributes.current_activity }}'
  - platform: ups
    username: mikegrb
    password: !secret ups_password
  - platform: octoprint
    name: OctoPrint
    monitored_conditions:
      - Current State
      - Job Percentage
  - platform: google_wifi
    monitored_conditions:
      - status
  - platform: speedtest
    minute: 30
    hour:
      - 6
    monitored_conditions:
      - ping
      - download
      - upload

  - platform: rest
    resource: https://solar.thegrebs.com/latest.json
    name: Solar Generation
    value_template: '{{ value_json.tot_solar }}'
    unit_of_measurement: kWh
    json_attributes:
      - tot_used


apple_tv:
  # Living Room
  - host: 192.168.86.208
    login_id: !secret apple_tv_login_id
    start_off: true
  # Office
  - host: 192.168.86.101
    login_id: !secret apple_tv_login_id
    start_off: true

octoprint:
  host:    192.168.86.120
  api_key: !secret octoprint_api_key

#media_player:
#  - platform: tivo
#    host: 192.168.86.215
#    name: Den Tivo
#    port: 31339
#    device: 0
#    debug: 0

media_player:
  - platform: alexa
    email: michael@thegrebs.com
    password: !secret amazon_pass
    url: amazon.com

switch:
  - platform: command_line
    switches:
      office_tv:
        friendly_name: Office TV
        command_on: 'curl -X POST http://192.168.86.223:8060/keypress/PowerOn'
        command_off: 'curl -X POST http://192.168.86.223:8060/keypress/PowerOff'
        command_state: 'curl -s GET http://192.168.86.223:8060/query/device-info | grep power-mode | sed -e "s:<power-mode>DisplayOff</power-mode>:OFF:" -e "s:<power-mode>PowerOn</power-mode>:ON:"'
        value_template: '{{ value == "ON" }}'
  - platform: mqtt
    name: "TJ's Desk Lamp"
    state_topic: "stat/tjs_desk/POWER"
    command_topic: "cmnd/tjs_desk/POWER"
    availability_topic: "tele/tjs_desk/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  - platform: mqtt
    name: "Lounge Fan"
    state_topic: "stat/lounge/fan/POWER"
    command_topic: "cmnd/lounge/fan/POWER"
    availability_topic: "tele/lounge/fan/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  - platform: mqtt
    name: "Audio Mixer"
    state_topic: "stat/office/audio_mixer/POWER"
    command_topic: "cmnd/office/audio_mixer/POWER"
    availability_topic: "tele/office/audio_mixer/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  - platform: mqtt
    name: "HF Radio"
    state_topic: "stat/office/hf_radio/POWER"
    command_topic: "cmnd/office/hf_radio/POWER"
    availability_topic: "tele/office/hf_radio/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

camera:
  - platform: generic
    name: RADAR
    still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=DIX&brand=wui&num=1&delay=15&type=N0R&frame=0&scale=1&noclutter=1&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=1&rainsnow=1&lightning=1&smooth=1&rand=25425955&lat=39.47&lon=-74.51&label=Pomona
  - platform: mjpeg
    name: OctoPrint
    still_image_url: http://192.168.86.120/webcam/?action=snapshot
    mjpeg_url: http://192.168.86.120/webcam/?action=stream
  - platform: uvc
    nvr: 192.168.86.126
    key: !secret uvc_api_key
    password: !secret uvc_pass

tts:
  - platform: google

notify:
  - name: twitter
    platform: twitter
    consumer_key: !secret twitter_consumer_key
    consumer_secret: !secret twitter_consumer_secret
    access_token: !secret twitter_access_token
    access_token_secret: !secret twitter_access_token_secret
  - name: all
    platform: group
    services:
      - service: ios_michaels_iphone
  - name: all_t
    platform: group
    services:
      - service: ios_michaels_iphone
      - service: twitter

juicenet:
  access_token: !secret juicenet_api_key

zone:
  - name: School
    latitude: 39.487062
    longitude: -74.515413
    radius: 300
    icon: mdi:school

cloud:
  alexa:
    filter:
      include_domains:
        - switch
        - light
        - fan
        - script
        - input_boolean
      exclude_entities:
        - light.den_2
        - light.den_3
        - light.office_2
        - light.office_3
        - light.fr_1
        - light.fr_1_2
        - light.fr_2
        - light.fr_2_2
        - light.front_room_2
        - light.entertainment_area_1
        - light.inside_lights
        - switch.outside_front
        - switch.outside_lights
        - light.outside
        - light.downstairs
        - light.outside
        - light.upstairs
    entity_config:
      script.fix_hall_light:
        name: Fix Hall Light
        display_categories: SWITCH
      script.sleep_imac:
        name: Sleep iMac
        display_categories: SWITCH
  google_actions:
    filter:
      include_domains:
        - switch
        - light
        - fan
        - script
      exclude_entities:
        - light.den_2
        - light.den_3
        - light.office_2
        - light.office_3
        - light.fr_1
        - light.fr_1_2
        - light.fr_2
        - light.fr_2_2
        - light.front_room_2
        - light.entertainment_area_1
        - light.inside_lights
        - switch.outside_front
        - switch.outside_lights
        - light.outside
        - light.downstairs
        - light.outside
        - light.upstairs
    entity_config:
      script.fix_hall_light:
        name: Fix Hall Light
      script.sleep_imac:
        name: Sleep iMac

alexa:

homekit:
  auto_start: False
  filter:
    include_domains:
      - switch
      - light
      - fan
      - lock
      - climate
    exclude_entities:
      - group.kitchen
      - light.den_2
      - light.den_3
      - light.office_2
      - light.office_3
      - light.fr_1
      - light.fr_1_2
      - light.fr_2
      - light.fr_2_2
      - light.front_room_2
      - light.entertainment_area_1
      - sensor.dark_sky_precip_probability
      - light.inside_lights
      - switch.outside_front
      - switch.outside_lights
      - light.outside
      - light.downstairs
      - light.outside
      - light.upstairs
      - climate.home_house_thermostat

input_number:
  btc_limit:
    name: Current BTC Limit Order
    initial: 0
    min: 0
    max: 999999999
    step: 1
    mode: box
    unit_of_measurement: BTC
    icon: mdi:currency-btc

input_boolean:
  kitchen_accent_motion_triggered:
    name: Kitchen Accent Turned on by motion
    initial: off

timer:
  kitchen_accent:
    duration: '00:10:00'

group:      !include groups.yaml
automation: !include_dir_merge_list automation/
script:     !include scripts.yaml
intent_script: !include alexa.yaml
