# give HA 3 minutes to discover devices
- alias: 'Start HomeKit'
  initial_state: on
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: 00:03  # Waits 3 minutes
    - service: homekit.start
