# Evening reminder to plug in the car if we are both home

- alias: Plug-In Car Reminder
  initial_state: on
  trigger:
    platform: time
    at: '18:30:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.juicenet_device_charging_status
        state: standby
      - condition: state
        entity_id: device_tracker.michaels_iphone
        state: home
  action:
    - service: tts.google_say
      data:
        entity_id: media_player.family_room_speaker
        message: The car is not plugged in.
    - service: notify.all_t
      data:
        message: The car is not plugged in.
